# Atividade 01 - Etapa 01

### Dados numéricos

In [67]:
#Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)
#dá-se o valor 1 à variável a

Valor de a = 1


int

In [69]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)
#dá-se o valor 1.0 à variável b, tornando-a uma variável de maior precisão, chamada de float

1.0


float

In [71]:
# Converter float para int
c = int(b)
print(c)
type(c)
#Usa-se o comando int para transformar a variável de float para int

1


int

In [72]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)
#Importa-se a biblioteca nu,py de arrays

nan


float

In [73]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)
#A primeira linha atribui à variável e o mesmo valor que está armazenado em d.
#A segunda linha incrementa o valor de d em 1 e atribui o resultado a e.
#A terceira linha calcula a soma dos elementos [d, 1], considerando possíveis valores NaN (Not a Number), e atribui o resultado a e.
#Cada resultado é impresso na saída padrão após cada operação.

nan
nan
1.0


In [75]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)
#Este código cria duas variáveis de texto, f contendo "Fábio" e g contendo "Gabriel". Em seguida, imprime o conteúdo dessas variáveis, primeiro f, depois g.
#Depois, ele imprime a concatenação das duas variáveis, ou seja, une o conteúdo de f e g em uma única string.
#Por último, ele imprime uma versão mais legível, onde f e g estão separados por um espaço.

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


### Dados tipo bool - lógica

In [76]:
a == 1
#Este código verifica se o valor da variável a é igual a 1. Se for, a expressão a == 1 retornará verdadeiro (True); caso contrário, retornará falso (False).

True

In [77]:
h = (a==1)
print(h)
type(h)
#A expressão `(a == 1)` verifica se o valor da variável `a` é igual a 1. Se for verdadeiro, `h` recebe o valor `True`; caso contrário, `h` recebe o valor `False`.
#Em seguida, o valor de `h` é impresso na saída padrão.
#`type(h)` retorna o tipo de dado de `h`, que será `<class 'bool'>`, indicando que `h` é uma variável booleana, ou seja, pode conter apenas os valores `True` ou `False`.

True


bool

In [78]:
h = (a==2)
print(h)
type(h)
#Este código verifica se o valor armazenado na variável a é igual a 2. O resultado dessa verificação, que será True se a for igual a 2 e False caso contrário, é atribuído à variável h. Em seguida, o valor de h é impresso e o tipo de dado de h é mostrado, revelando que h é um objeto do tipo booleano (True/False).

False


bool

In [79]:
i = True
type(i)
#Neste código, uma variável chamada i é definida como sendo igual a True, que é um valor booleano representando verdadeiro. Em seguida, a função type() é usada para determinar o tipo de dado da variável i, que neste caso é um tipo de dado booleano.

bool

In [81]:
ii = 'True'
type(ii)
#Este código primeiro atribui a string 'True' à variável ii, e depois usa a função type() para determinar o tipo de dado armazenado em ii, que é uma string.

str

### Operação de comparação

In [14]:
# Operação ==
a==b

True

In [15]:
# Operação ><
a>b

False

In [16]:
# Operação !=
a!=b

False

In [17]:
# Operação >= ou <=
a>=b

True

### Operações matemáticas

In [83]:
# Soma 
a+b
#Este código realiza a soma entre as duas variáveis traçadas

2.0

In [19]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [21]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [22]:
# Divisão
a/b

1.0

In [23]:
# Potencia
5**2

25

In [85]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)
#Este código importa o módulo `math` e em seguida calcula o valor de \( e^ {10} \) usando a função `exp()` do módulo `math`.

22026.465794806718

In [25]:
math.exp(0)

1.0

In [26]:
math.exp(a)

2.718281828459045

In [28]:
math.exp(-10)

4.5399929762484854e-05

In [29]:
import math as mt
mt.log(c)

0.0

In [30]:
mt.log10(100)

2.0

### Listas

In [86]:
myFirstList = [1,2,3]
print(myFirstList)
#Este código cria uma lista chamada `myFirstList` contendo os números 1, 2 e 3, e então imprime essa lista na saída padrão.

[1, 2, 3]


In [87]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])
#Este código imprime os valores armazenados em índices específicos de uma lista chamada `myFirstList`. 
#O primeiro `print(myFirstList[0])` imprime o valor armazenado no primeiro índice da lista (`0`).
#O segundo `print(myFirstList[2])` imprime o valor armazenado no terceiro índice da lista (`2`). 

1
3


In [33]:
myFirstList==a

False

In [34]:
myFirstList[0]==a

True

In [88]:
mySecList = [1,a,'c']
print(mySecList)
#Neste código, uma lista chamada `mySecList` é criada, contendo três elementos: o número 1, o valor contido na variável `a`, e a string 'c'. Em seguida, a lista `mySecList` é impressa na saída padrão.

[1, 1, 'c']


In [40]:
type(mySecList)

list

In [41]:
type(mySecList[2])

str

In [42]:
type(mySecList[1])

int

### Caminhos = path

In [89]:
path = r"C:\Users\Dell\OneDrive\Documentos\GitHub\Polatm_RamonVieira"
print(path)
#O código define um caminho de arquivo para um diretório chamado "Polatm_RamonVieira" dentro da estrutura de diretórios do usuário atual em um sistema Windows e imprime esse caminho na tela.

C:\Users\Dell\OneDrive\Documentos\GitHub\Polatm_RamonVieira


In [102]:
import os
# Listar arquivos na pasta
os.listdir(path)
#Este código mostra os arquivos existens na pasta selecionada

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'outputs',
 'README.md',
 'scripts',
 'venv']

In [45]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [47]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:\\Users\\Dell\\OneDrive\\Documentos\\GitHub\\Polatm_RamonVieira/.git'

In [103]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [104]:
# Diretório que estou trababalhando
os.getcwd()
#Demonstra o caminho usado no processo

'C:\\Users\\Dell\\OneDrive\\Documentos'

In [105]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\Dell\\OneDrive\\Documentos\\')
#Altera o caminho

In [106]:
os.getcwd()
#`os.getcwd()` retorna o diretório atual em que o programa está sendo executado.

'C:\\Users\\Dell\\OneDrive\\Documentos'

In [107]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
#Cria o novo caminho usando o path

diretório já existe


In [108]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

diretório já existe


### Numpy arrays e Pandas DataFrames

In [109]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)
#Este código cria um array NumPy contendo o número 0 e verifica o tipo desse array.

numpy.ndarray

In [110]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [112]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.47796078 0.36609365 0.94037788 0.52072671 0.90451573 0.74789764
  0.56195379 0.35575403 0.22283196 0.91027166]
 [0.91101081 0.8863507  0.49080765 0.43064455 0.48155293 0.08785784
  0.56437582 0.1635047  0.98998872 0.74355118]
 [0.0819955  0.34871407 0.35829817 0.0185841  0.67373456 0.64343369
  0.73423891 0.63562714 0.9504365  0.37841487]
 [0.92982221 0.79966485 0.64486574 0.3824666  0.87959468 0.07469163
  0.01408298 0.32184579 0.91971551 0.71215143]
 [0.02426417 0.08839363 0.42606631 0.01763228 0.17162648 0.45598763
  0.15812928 0.42460214 0.62555761 0.37853606]
 [0.06455801 0.54008181 0.28951143 0.68345942 0.782422   0.31770945
  0.83281569 0.4166736  0.68748335 0.89607736]
 [0.99305798 0.16859119 0.10162668 0.55448962 0.61120183 0.23413897
  0.75562602 0.8534909  0.76324261 0.64394846]
 [0.77347619 0.00794742 0.48833374 0.95075782 0.61619449 0.55833953
  0.86416281 0.82282246 0.8664947  0.12150143]
 [0.7945484  0.25648912 0.21688285 0.7679364  0.58082471 0.18384633
  0.71750105

In [113]:
# Acessando valores da matriz
n[0,:]

array([0.47796078, 0.36609365, 0.94037788, 0.52072671, 0.90451573,
       0.74789764, 0.56195379, 0.35575403, 0.22283196, 0.91027166])

In [117]:
n[:,0]
#`n[:,0]` extrai todos os elementos da primeira coluna de uma matriz bidimensional `n` e retorna-os como um vetor unidimensional.

array([0.47796078, 0.91101081, 0.0819955 , 0.92982221, 0.02426417,
       0.06455801, 0.99305798, 0.77347619, 0.7945484 , 0.04189598])

In [115]:
n[:,1:5]

array([[0.36609365, 0.94037788, 0.52072671, 0.90451573],
       [0.8863507 , 0.49080765, 0.43064455, 0.48155293],
       [0.34871407, 0.35829817, 0.0185841 , 0.67373456],
       [0.79966485, 0.64486574, 0.3824666 , 0.87959468],
       [0.08839363, 0.42606631, 0.01763228, 0.17162648],
       [0.54008181, 0.28951143, 0.68345942, 0.782422  ],
       [0.16859119, 0.10162668, 0.55448962, 0.61120183],
       [0.00794742, 0.48833374, 0.95075782, 0.61619449],
       [0.25648912, 0.21688285, 0.7679364 , 0.58082471],
       [0.3600242 , 0.98194485, 0.61628533, 0.54407952]])

In [116]:
n[0,1:5]

array([0.36609365, 0.94037788, 0.52072671, 0.90451573])

In [63]:
n[0,-1]

0.34415345214772675

In [64]:
n[0,4:-1]

array([0.53955726, 0.30360227, 0.53532288, 0.72741791, 0.67595598])

In [65]:
n[0,4:]

array([0.53955726, 0.30360227, 0.53532288, 0.72741791, 0.67595598,
       0.34415345])

In [118]:
an = np.log(n*5)
print(an)
#O código calcula o logaritmo natural do produto de `n` por 5 usando o pacote numpy em Python, e imprime o resultado.

[[ 0.8712113   0.60457182  1.54796443  0.95690799  1.50908233  1.31894876
   1.03310225  0.57592219  0.10810059  1.51542572]
 [ 1.5162374   1.48879533  0.89773494  0.76696567  0.87869878 -0.82259726
   1.037403   -0.20147564  1.59937619  1.31312024]
 [-0.89165294  0.55593495  0.58304814 -2.37601112  1.21451884  1.1685016
   1.30051709  1.15629476  1.55860399  0.63767378]
 [ 1.53667603  1.38587533  1.17072477  0.64832396  1.48114384 -0.98494938
  -2.65335049  0.47575514  1.52574703  1.26997321]
 [-2.10931672 -0.81651742  0.75627762 -2.42858595 -0.15299689  0.82414832
  -0.23490447  0.75283521  1.14032607  0.63799397]
 [-1.13075323  0.99340326  0.36987743  1.22884992  1.36407687  0.46281993
   1.42649499  0.73398582  1.23472025  1.49970938]
 [ 1.60247168 -0.17084056 -0.67701126  1.01973073  1.11710987  0.15759744
   1.3292292   1.45101751  1.33925858  1.16930132]
 [ 1.35257752 -3.22546955  0.8926817   1.55894201  1.12524528  1.02664989
   1.46344382  1.41442309  1.46613863 -0.49839131]
 